src/main/java/br/com/byter/model/Mensageiro.java
package br.com.byter.model;

public interface Mensageiro {
	public void enviarMensagem(String mensagem);
}

src/main/java/br/com/byter/model/MensageiroCorreio.java
package br.com.byter.model;

public class MensageiroCorreio implements Mensageiro{

	@Override
	public void enviarMensagem(String mensagem) {
		System.out.println("Enviando mensagem por correio:"+ mensagem);
		
	}

}

src/main/java/br/com/byter/model/MensageiroSMS.java
package br.com.byter.model;

@br.com.byter.qualificadores.MensageiroSMS
public class MensageiroSMS implements Mensageiro {

	@Override
	public void enviarMensagem(String mensagem) {
		System.out.println("Enviando mensagem por sms: " + mensagem);

	}

}

src/main/java/br/com/byter/controller/EnvioMensagemBean.java
package br.com.byter.controller;

import javax.enterprise.context.RequestScoped;
import javax.enterprise.inject.Default;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.byter.model.Mensageiro;
import br.com.byter.qualificadores.MensageiroSMS;

@Named("enviarMensagemBean")
@RequestScoped
public class EnvioMensagemBean {

	@Inject @MensageiroSMS //@Default
	private Mensageiro mensageiro;
	
	private String texto;
	
	public void enviarMensagem(){
		mensageiro.enviarMensagem(texto);
	}

	public String getTexto() {
		return texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}	
}

src/main/java/br/com/byter/controller/FormatacaoBean.java
package br.com.byter.controller;

import java.text.DateFormat;
import java.util.Date;

import javax.inject.Inject;
import javax.inject.Named;

import br.com.byter.qualificadores.Brasil;

@Named
@javax.faces.view.ViewScoped
public class FormatacaoBean {

	@Inject@Brasil
	private DateFormat formatadorData;
	
	private Date dataInformada;
	private String dataFormatada;
	
	public void enviar(){
		dataFormatada = formatadorData.format(dataInformada);
	}

	public Date getDataInformada() {
		return dataInformada;
	}

	public void setDataInformada(Date dataInformada) {
		this.dataInformada = dataInformada;
	}

	public String getDataFormatada() {
		return dataFormatada;
	}

	public void setDataFormatada(String dataFormatada) {
		this.dataFormatada = dataFormatada;
	}	
}

src/main/java/br/com/byter/controller/PrecoProdutoBean.java
package br.com.byter.controller;

import javax.inject.Inject;
import javax.inject.Named;

import br.com.byter.service.CalculadoraPreco;

@Named("meuBean")
public class PrecoProdutoBean {

	@Inject
	private CalculadoraPreco calculadora;
	
	public double getPreco(){
		return calculadora.calcularPreco(12,44.55);
	}
	
}

src/main/java/br/com/byter/controller/TesteBean.java
package br.com.byter.controller;

import javax.enterprise.context.RequestScoped;
import javax.enterprise.inject.Default;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.byter.exception.NegocioException;
import br.com.byter.model.Mensageiro;
import br.com.byter.qualificadores.MensageiroSMS;

@Named("testeBean")
@RequestScoped
public class TesteBean {
	public void salvar(){
		throw new NegocioException("Mensagem"); 
	}
	
	public void salvar2(){
		throw new RuntimeException("Mensagem"); 
	}
}

src/main/webapp/404.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>SENTINEL BLUE | Prime Faces Layouts Header</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
        
    <h:outputStylesheet name="css/font-icon-layout.css" library="sentinel-layout" />
    <h:outputStylesheet name="css/sentinel-layout.css" library="sentinel-layout" />
    <h:outputStylesheet name="css/core-layout.css" library="sentinel-layout" />
</h:head>

<h:body class="fontRegular red-back">
    
    <div class="Container100 Top20Percent PosAbsolute MarAuto OvHidden">
        <div class="Wid50 MarAuto OvHidden TexAlCenter">
            <h:graphicImage name="images/error-face.svg" library="sentinel-layout" style="width: 100px;"/>
            <div class="EmptyBox20"></div>
            <span class="white Fs100 Wid100 DispBlock">404</span>
            <span class="white Wid100 DispBlock Fs24">Page Not Found !</span><br/>
            <span class="white Wid100 DispBlock Fs12">Sorry, but the resource you are looking for has not been found.<br/>
            </span>
            <div class="EmptyBox20"></div>
            <p:button value="Back to Dashboard" styleClass="Fs24" href="dashboard.xhtml"></p:button>
            <div class="EmptyBox50"></div>
        </div>
    </div>
    
</h:body>

</html>

src/main/webapp/EnviarMensagem.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</h:head>
<h:body>
	<h:form>
		<h:inputText value="#{enviarMensagemBean.texto}" />
		<p:commandButton value="Enviar Mensagem" actionListener="#{enviarMensagemBean.enviarMensagem}"></p:commandButton>
	</h:form>
</h:body>
</html>

src/main/webapp/PrecoProduto.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</h:head>
<h:body>

	<h:form>
		<h:outputText value="#{meuBean.preco}" />
	</h:form>

</h:body>
</html>

src/main/webapp/WEB-INF/leftmenu.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ps="http://primefaces.org/sentinel"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">
    
    <div id="layout-menubar" class="Unselectable fontRegular">
        <div class="layout-menubarinner-box" id="buttonArea">
            <a href="#" id="layout-menubar-resize" class="BordRad3" title="Menu Resize"><i class="icon-th-list-2"></i></a>
            <a href="#" id="layout-menubar-resize2" class="BordRad3" title="Open Menu"><i class="icon-menu"></i></a>
        </div>

        <div class="layout-menubarinner-box" id="searchArea">
            <i class="icon-search floatLeft gray"></i>
            <input type="text" class="layout-menubar-search floatLeft Animated05" placeholder="Search Here"/>
        </div>
        
       <!--   <h:form>
         	<ps:menu  model="#{menuPrimeFacesMB.menuPrimeFaces}" id="panelMenu"/>           	
         </h:form> -->
        <ps:menu id="sm_leftmenu">
            <p:menuitem id="sm_dashboard" value="Dashboard" icon="icon-home-outline" outcome="dashboard" containerStyleClass="layout-menubar-active"/>
            <p:submenu id="sm_sentineltheme" label="Sentinel Theme" icon="icon-gauge" >
                <p:menuitem id="sm_forms" value="Forms" icon="icon-doc-text-1" outcome="forms"/>
                <p:menuitem id="sm_datacomponents" value="Data Components" icon="icon-th" outcome="data"/>
                <p:menuitem id="sm_datatable" value="DataTable" icon="icon-table" outcome="datatable"/>
                <p:menuitem id="sm_panels" value="Panels" icon="icon-magic" outcome="panel"/>
                <p:menuitem id="sm_overlays" value="Overlays" icon="icon-newspaper" outcome="overlay"/>
                <p:menuitem id="sm_menus" value="Menus" icon="icon-menu" outcome="menu"/>
                <p:menuitem id="sm_messages" value="Messages" icon="icon-bell" outcome="messages"/>
                <p:menuitem id="sm_fu" value="FileUpload" icon="icon-docs" outcome="file"/>
                <p:menuitem id="sm_misc" value="Misc" icon="icon-beaker" outcome="misc"/>
            </p:submenu>
            <p:submenu id="sm_dp" label="Default Pages" icon="icon-pin-outline">
                <p:menuitem id="sm_empty" value="Empty Page" icon="icon-plus-squared-alt" outcome="empty-page"/>
                <p:menuitem id="sm_login" value="Login Page" icon="icon-login" outcome="login"/>
                <p:menuitem id="sm_error" value="Error Page" icon="icon-warning-empty" outcome="error" />
                <p:menuitem id="sm_404" value="404 Page" icon="icon-warning-empty" outcome="404"/>
                <p:menuitem id="sm_access" value="Access Denied Page" icon="icon-warning-empty" outcome="access-denied"/>
            </p:submenu>
            <p:submenu id="sm_menu" label="Menu Hierarchy" icon="icon-sitemap">
                <p:submenu id="sm_sub1" label="Submenu 1" icon="icon-folder-empty">
                    <p:submenu id="sm_sub1_1" label="Submenu 1.1" icon="icon-folder-empty">
                        <p:submenu id="sm_sub1_1_1" label="Submenu 1.1.1" icon="icon-folder-empty">
                            <p:menuitem id="sm_lnk1" value="Link 1" icon="icon-link" outcome="empty-page.xhtml"/>
                            <p:menuitem id="sm_lnk2" value="Link 2" icon="icon-link" outcome="empty-page.xhtml" />
                            <p:menuitem id="sm_lnk3" value="Link 3" icon="icon-link" outcome="empty-page.xhtml" />
                        </p:submenu>
                    </p:submenu>
                </p:submenu>
            </p:submenu>
            <p:menuitem id="sm_fonts" value="Font Icons" icon="icon-book" outcome="font-icons.xhtml" />
            <p:menuitem id="sm_user" value="User Profile" icon="icon-vcard" outcome="empty-page" />
            <p:menuitem id="sm_tasks" value="Tasks" icon="icon-tasks" outcome="empty-page" />
            <p:menuitem id="sm_contact" value="Contact" icon="icon-phone" outcome="empty-page" />
            <p:menuitem id="sm_doc" value="Documentation" icon="icon-graduation-cap" outcome="documentation" />           	
        </ps:menu>          
    </div>
</ui:composition>

src/main/webapp/WEB-INF/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

    <h:head>
        <f:facet name="first">
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
            <meta name="apple-mobile-web-app-capable" content="yes" />
        </f:facet>
        <title>PrimeFaces Sentinel</title>
        <h:outputScript name="js/layout.js" library="sentinel-layout" />
        <h:outputScript library="js" name="jquery.maskMoney.js"/>
        <ui:insert name="head" />
    </h:head>

    <h:body>        
        <ui:include src="topbar.xhtml" />

        <ui:include src="leftmenu.xhtml" />

        <div id="layout-portlets-cover" class="fontRegular">
            <ui:insert name="content">
               Template
            </ui:insert>
        </div>
        
        <p:ajaxStatus style="width:32px; height:32px; 
        			  position:fixed; right:12px; bottom:10px" onsuccess="configurarMoeda()">
            <f:facet name="start">
                <p:graphicImage name="images/preloader.gif" library="sentinel-layout"/>
            </f:facet>

            <f:facet name="complete">
                <h:outputText value="" />
            </f:facet>
        </p:ajaxStatus>
        
        <script>
			function configurarMoeda() {
				$(".moeda").maskMoney({ decimal: ",", thousands: ".", allowZero: true });
			}
			
			$(document).ready(function() {
				configurarMoeda();
			});
		</script>

        <h:outputStylesheet name="css/font-icon-layout.css" library="sentinel-layout" />
        <h:outputStylesheet name="css/sentinel-layout.css" library="sentinel-layout" />
        <h:outputStylesheet name="css/core-layout.css" library="sentinel-layout" />
    </h:body>
</html>

src/main/webapp/WEB-INF/topbar.xhtml
<ui:composition 

    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
     xmlns:p="http://primefaces.org/ui">
    
    
    <div id="layout-header" class="Unselectable fontRegular">
    
    	<p:growl id="msg"/>	
    
    	<!--  <h:form>		   
				<p:ajaxStatus	style="width:10px;height:10px;position:absolute;top:1px;right:90px;z-index:1;">
					<f:facet name="start">				
						<h:panelGrid columns="1">
							<h:graphicImage  name="images/animation.gif"   width="38"	height="38"  library="sentinel-layout"/>							
						</h:panelGrid>				
					</f:facet>
		
					<f:facet name="complete">
						<h:outputText value="" />
					</f:facet>
				</p:ajaxStatus>			
		</h:form>		  -->
    
        <a href="#{request.contextPath}/dashboard.xhtml" id="layout-logo">
            <h:graphicImage name="images/LOGO.svg" styleClass="Fleft" library="sentinel-layout"/>
            <span class="Fs19 FontTitilliumSemiBoldItalic Fleft"><span class="hardblue">SENTINEL</span><span class="softblue"> SOFT</span></span>
        </a>
    	<ul id="sm-topmenu" class="layout-header-widgets white Fs14">
    		 <li class="Fleft BordRadHalf TexAlCenter"><i class="icon-user-male"></i>
    			<ul class="layout-header-widgets-submenu BordRad5 shadows white Animated05">
    				<li class="Animated05"><a class="white Unselectable"><i class="icon-user-male Fs26 OvHidden"></i><span class="Fs18">Walter White<br/><span class="Fs10">Last Login - 18.08.2014</span></span></a></li>
    				<li class="Animated05"><a href="#" class="white Unselectable"><i class="icon-stopwatch-1"></i>User Tasks</a></li>
    				<li class="Animated05"><a href="#" class="white Unselectable"><i class="icon-users-2"></i>Create New User</a></li>
    				<li class="Animated05"><a href="#" class="white Unselectable"><i class="icon-sliders"></i>User Preferences</a></li>
    			</ul>
    		</li>
    		<li class="Fleft BordRadHalf TexAlCenter"><i class="icon-mail"></i><span class="alertBubble BordRad10 Fs9">166</span>
    			<ul class="layout-header-widgets-submenu BordRad5 shadows white Animated05">
    				<li class="Animated05"><a href="#" class="white Unselectable TexAlRight"><i class="icon-chat-empty yellow"></i>Gustavo Fring<br/><span class="Fs10">What does a man do Walter?</span></a></li>
    				<li class="Animated05"><a href="#" class="white Unselectable TexAlRight"><i class="icon-chat-empty"></i>Skyler White<br/><span class="Fs10">Where are you?.</span></a></li>
    				<li class="Animated05"><a href="#" class="white Unselectable TexAlRight"><i class="icon-chat-empty red"></i>Hank Schrader<br/><span class="Fs10">Barbecue photos from last weekend.</span></a></li>
    				<li class="Animated05"><a href="#" class="white Unselectable TexAlRight"><i class="icon-chat-empty red"></i>Jesse Pinkman<br/><span class="Fs10">Mr. White.</span></a></li>
    				<li class="Animated05"><a href="#" class="white Unselectable TexAlRight"><i class="icon-chat-empty"></i>Heisenberg<br/><span class="Fs10">I am the one who knocks.</span></a></li>
    			</ul>
    		</li>
    		<li class="Fleft BordRadHalf TexAlCenter"><i class="icon-bell"></i><span class="alertBubble BordRad10 Fs9">24</span>
    			<ul class="layout-header-widgets-submenu BordRad5 shadows white Animated05">
    				<li class="Animated05"><a href="#" class="white Unselectable TexAlRight"><i class="icon-flag red"></i>New Products</a></li>
    				<li class="Animated05"><a href="#" class="white Unselectable TexAlRight"><i class="icon-flag yellow"></i>Today Sales Reports</a></li>
    				<li class="Animated05"><a href="#" class="white Unselectable TexAlRight"><i class="icon-flag red"></i>Visit Reports</a></li>
    				<li class="Animated05"><a href="#" class="white Unselectable TexAlRight"><i class="icon-flag red"></i>Sales Reports</a></li>
    				<li class="Animated05"><a href="#" class="white Unselectable TexAlRight"><i class="icon-flag"></i>Task Alerts</a></li>
    			</ul>
    		</li>
    		<li class="Fleft BordRadHalf TexAlCenter"><i class="icon-wrench-1"></i>
    			<ul class="layout-header-widgets-submenu BordRad5 shadows white Animated05">
    				<li class="Animated05"><a href="#" class="white Unselectable"><i class="icon-sun"></i>System Settings</a></li>
    				<li class="Animated05"><a href="#" class="white Unselectable"><i class="icon-lifebuoy"></i>Help Desk</a></li>
    			</ul>
    		</li>
    		<li class="Fleft BordRadHalf TexAlCenter"><i class="icon-power"></i>
    			<ul class="layout-header-widgets-submenu BordRad5 shadows white Animated05">    				
    				<!-- <li class="Animated05"><a href="#" class="white Unselectable"><i class="icon-logout"></i>Log Out</a></li> -->
    				<h:form>
    				<li class="Animated05"><h:commandLink styleClass="white Unselectable" action="#{loginMB.sair()}"><i class="icon-logout"></i>Log Out</h:commandLink></li>
    				</h:form>    				
    			</ul>
    		</li>
    	</ul>
    	<!-- NEVER REMOVE FOLLOWING 'UL' TAG ! BECAUSE THIS CONTAINS RESPONSIVE MODE HEADER MENU OPEN-CLOSE BUTTON -->
    	<ul id="sm-mobiletopmenu" class="layout-header-widgets white Fs14">
    		<li class="Fleft BordRadHalf TexAlCenter Animated05 DisplayOnResponsive"><i class="icon-th-1"></i></li>
    	</ul>
    	<!-- ****** -->
   	</div>    
</ui:composition>

src/main/webapp/access-denied.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>SENTINEL BLUE | Prime Faces Layouts Header</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
        
    <h:outputStylesheet name="css/font-icon-layout.css" library="sentinel-layout" />
    <h:outputStylesheet name="css/sentinel-layout.css" library="sentinel-layout" />
    <h:outputStylesheet name="css/core-layout.css" library="sentinel-layout" />
</h:head>

<h:body class="fontRegular red-back">
    
    <div class="Container100 Top20Percent PosAbsolute MarAuto OvHidden">
        <div class="Wid50 MarAuto OvHidden TexAlCenter">
            <h:graphicImage name="images/access-denied.svg" library="sentinel-layout" style="width: 140px;"/>
            <div class="EmptyBox20"></div>
            <span class="white Fs60 Wid100 DispBlock">Access Denied</span>
            <span class="white Wid100 DispBlock Fs24">Please Check Your Permissions !</span><br/>
            <span class="white Wid100 DispBlock Fs12">Sorry, but you have no access to this page.<br/>
            </span>
            <div class="EmptyBox20"></div>
            <p:button value="Back to Dashboard" styleClass="Fs24" href="dashboard.xhtml"></p:button>
            <div class="EmptyBox50"></div>
        </div>
    </div>
    
</h:body>

</html>

src/main/webapp/datatable.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template.xhtml">

    <ui:define name="content">
        <div class="ContainerIndent">
            <p:panel>
                <div class="ContainerIndent">
                    <h:form id="form">
                        <p:dataTable id="singleDT" var="car" value="#{carsView.cars}" selectionMode="single" selection="#{carsView.selectedCar}" rowKey="#{car.id}"
                                     rows="10" paginator="true" paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                     rowsPerPageTemplate="5,10,15" emptyMessage="No cars found with given criteria" reflow="true">
                            <f:facet name="header">
                                DataTable
                            </f:facet>

                            <p:column headerText="Id" sortBy="#{car.id}">
                                <h:outputText value="#{car.id}" />
                            </p:column>
                            <p:column headerText="Year" sortBy="#{car.year}">
                                <h:outputText value="#{car.year}" />
                            </p:column>
                            <p:column headerText="Brand" sortBy="#{car.brand}">
                                <h:outputText value="#{car.brand}" />
                            </p:column>
                            <p:column headerText="Color" sortBy="#{car.color}">
                                <h:outputText value="#{car.color}" />
                            </p:column>
                            <f:facet name="footer">
                                <p:commandButton process="singleDT" update=":form:carDetail" value="View" oncomplete="PF('carDialog').show()" />
                            </f:facet>
                        </p:dataTable>

                        <p:dialog header="Car Info" widgetVar="carDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                            <p:outputPanel id="carDetail" style="text-align:center;">
                                <p:panelGrid  columns="2" rendered="#{not empty carsView.selectedCar}">
                                    <h:outputText value="Id:" />
                                    <h:outputText value="#{carsView.selectedCar.id}" />

                                    <h:outputText value="Year" />
                                    <h:outputText value="#{carsView.selectedCar.year}" />

                                    <h:outputText value="Color:" />
                                    <h:outputText value="#{carsView.selectedCar.color}" style="color:#{carsView.selectedCar.color}"/>

                                    <h:outputText value="Price" />
                                    <h:outputText value="\$#{carsView.selectedCar.price}" />
                                </p:panelGrid>
                            </p:outputPanel>
                        </p:dialog>

                        <div class="EmptyBox20"></div>

                    </h:form>
                </div>
            </p:panel>

            <div class="EmptyBox20"></div>

        </div>
    </ui:define>

</ui:composition>

src/main/webapp/empty-page.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template.xhtml">	

	<ui:define name="content">
      
    </ui:define>
</ui:composition>

src/main/webapp/file.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template.xhtml">

    <ui:define name="content">
        <div class="ContainerIndent">
            <p:panel header="FileUpload Samples">
                <div class="ContainerIndent">

                    <h3 class="hardblue">Multiple Sample</h3>
                    <h:form>
                        <p:fileUpload fileUploadListener="#{fileUploadView.handleFileUpload}" mode="advanced" dragDropSupport="false"
                                      multiple="true" update="messages" sizeLimit="100000" fileLimit="3" allowTypes="/(\.|\/)(gif|jpe?g|png)$/" />

                        <p:growl id="messages" showDetail="true" />
                    </h:form>

                </div>
            </p:panel>
        </div>
    </ui:define>

</ui:composition>

src/main/webapp/formatacao.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</h:head>
<h:body>

	<h:form>
		<p:calendar value="#{formatacaoBean.dataInformada}" pattern="dd/MM/yyyy" />
		<p:commandButton value="Enviar" action="#{formatacaoBean.enviar}" update="@form" />
		
		<br/>
		<h:outputText value="#{formatacaoBean.dataFormatada}" />
	</h:form>

</h:body>
</html>

src/main/webapp/messages.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template.xhtml">

    <ui:define name="content">

        <div class="ContainerIndent">
            <p:panel header="Messages Samples">
                <div class="ContainerIndent">

                    <p:panel>
                        <p:tooltip />

                        <h:form>
                            <p:messages showDetail="true" autoUpdate="true" closable="true" />

                            <p:commandButton value="Info" actionListener="#{messagesView.info}" />
                            <p:commandButton value="Warn" actionListener="#{messagesView.warn}" />
                            <p:commandButton value="Error" actionListener="#{messagesView.error}" />
                            <p:commandButton value="Fatal" actionListener="#{messagesView.fatal}" />
                        </h:form>

                        <p:separator />

                        <h:form>
                            <p:growl id="growl" showDetail="true" sticky="true" /> 

                            <h:panelGrid id="grid" columns="3" cellpadding="5">
                                <p:outputLabel for="default" value="Default:" />
                                <p:inputText id="default" required="true" />
                                <p:message for="default" />

                                <p:outputLabel for="txt" value="Text:" />
                                <p:inputText id="txt" required="true" />
                                <p:message for="txt" display="text" />

                                <p:outputLabel for="icon" value="Icon:" />
                                <p:inputText id="icon" required="true" />
                                <p:message for="icon" display="icon" />

                                <p:outputLabel for="tt" value="Tooltip:" />
                                <p:inputText id="tt" required="true" />
                                <p:message for="tt" display="tooltip" />
                            </h:panelGrid>

                            <p:commandButton id="submitButton" value="Submit" actionListener="#{messagesView.growlMessage}" update="grid growl" />
                        </h:form>
                    </p:panel> 

                </div>
            </p:panel>
        </div>

    </ui:define>

</ui:composition>